prepare:
  input_file: "data/raw/Tesla.csv"
  output_file: "data/processed/cleaned.csv"
  features_to_drop: ["Adj Close"]
  
train:
  n_estimators: 100
  max_depth: 5
  random_state: 42

evaluate:
  metrics_file: "metrics/eval.json"